In [43]:
# Imports
import os
import pandas as pd
import numpy as np
import re
PUIdata = os.getenv('PUIDATA')
# number of complains by community district

In [ ]:
# https://github.com/fedhere/PUI2016_fb55/blob/master/Lab8_fb55/PUI%202016%20-%20Working%20with%20Data%20Lab.ipynb

In [188]:
# Reading the data directly from the facility through compute
complainCalls = pandas.read_csv('/projects/open/NYCOpenData/nycopendata/data/erm2-nwe9/1446832678/erm2-nwe9')

In [189]:
# Visually inspecting the columns
complainCalls.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,31911011,11/05/2015 02:59:15 AM,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,11224,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.573431,-73.991742,"(40.57343122248129, -73.99174247588253)"
1,31908754,11/05/2015 02:09:49 AM,NaN,CHALL,CHALL,Opinion for the Mayor,HOUSING,NaN,NaN,NaN,...,NaN,NaN,NaN,1-1-1173130914,NaN,NaN,NaN,NaN,NaN,NaN
2,31910423,11/05/2015 02:06:51 AM,NaN,DPR,Department of Parks and Recreation,Root/Sewer/Sidewalk Condition,Trees and Sidewalks Program,Street,11234,1157 EAST 57 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.625004,-73.920726,"(40.62500363580505, -73.92072558378698)"
3,31909924,11/05/2015 02:02:20 AM,NaN,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11218,722 EAST 4 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.634522,-73.974790,"(40.634522428879706, -73.97479041437481)"
4,31913310,11/05/2015 01:57:20 AM,11/05/2015 01:57:31 AM,HRA,HRA Benefit Card Replacement,Benefit Card Replacement,Medicaid,NYC Street Address,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [190]:
# Explore the dateset columns
print (complainCalls.columns)

# There is a column for community board, display content
complainCalls['Community Board'][0]

Index([u'Unique Key', u'Created Date', u'Closed Date', u'Agency',
       u'Agency Name', u'Complaint Type', u'Descriptor', u'Location Type',
       u'Incident Zip', u'Incident Address', u'Street Name', u'Cross Street 1',
       u'Cross Street 2', u'Intersection Street 1', u'Intersection Street 2',
       u'Address Type', u'City', u'Landmark', u'Facility Type', u'Status',
       u'Due Date', u'Resolution Description',
       u'Resolution Action Updated Date', u'Community Board', u'Borough',
       u'X Coordinate (State Plane)', u'Y Coordinate (State Plane)',
       u'Park Facility Name', u'Park Borough', u'School Name',
       u'School Number', u'School Region', u'School Code',
       u'School Phone Number', u'School Address', u'School City',
       u'School State', u'School Zip', u'School Not Found',
       u'School or Citywide Complaint', u'Vehicle Type',
       u'Taxi Company Borough', u'Taxi Pick Up Location',
       u'Bridge Highway Name', u'Bridge Highway Direction', u'Road Ramp',
       u'Bridge Highway Segment', u'Garage Lot Name', u'Ferry Direction',
       u'Ferry Terminal Name', u'Latitude', u'Longitude', u'Location'],
      dtype='object')

'13 BROOKLYN'

In [191]:
# Check if all Boroughs and Community Districts are represented in the Data
uniqueCommunityDistricts = complainCalls['Community Board'].unique()

In [25]:
# How many community districts are represented

# There are 59 community districts
# https://www1.nyc.gov/site/planning/community/community-portal.page

# There is one unspecified for each borough (5) plus one general unspeciffied

type(uniqueCommunityDistricts)

uniqueCommunityDistricts.sort()
print (uniqueCommunityDistricts)
print (len(uniqueCommunityDistricts))


# There are community districits that do not exists (such as anything above 18)
# 26 BRONX' '27 BRONX' '28 BRONX' '55 BROOKLYN' '56 BROOKLYN' '64 MANHATTAN'
# 80 QUEENS' '81 QUEENS' '82 QUEENS' '83 QUEENS' '84 QUEENS'
# 95 STATEN ISLAND' 'Unspecified BRONX' 'Unspecified BROOKLYN'

# For the ones that are "wrong" we can put them togheter in a different column
# Can we get the percentage of the unspecified ones

['0 Unspecified' '01 BRONX' '01 BROOKLYN' '01 MANHATTAN' '01 QUEENS'
 '01 STATEN ISLAND' '02 BRONX' '02 BROOKLYN' '02 MANHATTAN' '02 QUEENS'
 '02 STATEN ISLAND' '03 BRONX' '03 BROOKLYN' '03 MANHATTAN' '03 QUEENS'
 '03 STATEN ISLAND' '04 BRONX' '04 BROOKLYN' '04 MANHATTAN' '04 QUEENS'
 '05 BRONX' '05 BROOKLYN' '05 MANHATTAN' '05 QUEENS' '06 BRONX'
 '06 BROOKLYN' '06 MANHATTAN' '06 QUEENS' '07 BRONX' '07 BROOKLYN'
 '07 MANHATTAN' '07 QUEENS' '08 BRONX' '08 BROOKLYN' '08 MANHATTAN'
 '08 QUEENS' '09 BRONX' '09 BROOKLYN' '09 MANHATTAN' '09 QUEENS' '10 BRONX'
 '10 BROOKLYN' '10 MANHATTAN' '10 QUEENS' '11 BRONX' '11 BROOKLYN'
 '11 MANHATTAN' '11 QUEENS' '12 BRONX' '12 BROOKLYN' '12 MANHATTAN'
 '12 QUEENS' '13 BROOKLYN' '13 QUEENS' '14 BROOKLYN' '14 QUEENS'
 '15 BROOKLYN' '16 BROOKLYN' '17 BROOKLYN' '18 BROOKLYN' '26 BRONX'
 '27 BRONX' '28 BRONX' '55 BROOKLYN' '56 BROOKLYN' '64 MANHATTAN'
 '80 QUEENS' '81 QUEENS' '82 QUEENS' '83 QUEENS' '84 QUEENS'
 '95 STATEN ISLAND' 'Unspecified BRONX' 'Unspecified BROOKLYN'
 'Unspecified MANHATTAN' 'Unspecified QUEENS' 'Unspecified STATEN ISLAND']
77

In [192]:
# Print total number of unique records
print (len(complainCalls['Unique Key'].unique()))

# Print total number of records
print (len(complainCalls))

# They are different! -> there are duplicates

10187744
10187766

In [195]:
# Drop Duplicates
complainCalls = complainCalls.drop_duplicates(['Unique Key'])

In [225]:
# Print len to verify that duplicates were dropped
print (len(complainCalls))

10187744

In [205]:
# Verify Missing Values (where value of the the actual cell is null)
# And see if we detect a patern
complainCallsNullValues = complainCalls.isnull().sum()

In [209]:
# Explore missing values
print (complainCallsNullValues)

Unique Key                               0
Created Date                             0
Closed Date                         450879
Agency                                   0
Agency Name                              0
Complaint Type                           0
Descriptor                           31057
Location Type                      3067596
Incident Zip                        794159
Incident Address                   2197705
Street Name                        2198558
Cross Street 1                     2375942
Cross Street 2                     2425792
Intersection Street 1              8345267
Intersection Street 2              8346281
Address Type                        490299
City                                788712
Landmark                          10180434
Facility Type                      8579463
Status                                   0
Due Date                           7120286
Resolution Description             3786739
Resolution Action Updated Date      250932
Community Board                          0
Borough                                  0
X Coordinate (State Plane)          878752
Y Coordinate (State Plane)          878752
Park Facility Name                       0
Park Borough                             0
School Name                              0
School Number                         2283
School Region                        56197
School Code                          56196
School Phone Number                      0
School Address                           6
School City                              0
School State                             0
School Zip                               5
School Not Found                   7151698
School or Citywide Complaint      10185390
Vehicle Type                      10180242
Taxi Company Borough              10177579
Taxi Pick Up Location             10089185
Bridge Highway Name               10152649
Bridge Highway Direction          10152701
Road Ramp                         10152964
Bridge Highway Segment            10135758
Garage Lot Name                   10183411
Ferry Direction                   10185001
Ferry Terminal Name               10181220
Latitude                            878752
Longitude                           878752
Location                            878752
dtype: int64

##### Missing Values:

There is a number of columns that do not have any missing values (Unique Key, Created Data, Agency, Etc.) These values might be generated automatatically by the tool used to capture the date (maybe unique id, agency name) or might be mandatory for entering a complain (maybe complain type)

On the columns with missing values there seems to be certain grouping on the geolocation like columns, such as X coordinate, Y coordinate, Latitude, Longitude and Location, as they all share the same number of missing values. Maybe this is also related to the data entry too: when you put a location these are all filled in in batch or so.

In [244]:
# Create a marker column (that will be filled in with true or false)
complainCalls["isValidBoard"] = np.ones(len(complainCalls.Borough), np.float)

# Valid Community Boards start with two digits that go from 0 to 18
# We can use a regular expression that gets only these values:
# [01]\d -> 01 matches a single character in the list 01, and \d matches a digit (equal to [0-9])

for bname in uniqueCommunityDistricts:
    if re.match(r"[01]\d", bname) == None:
        complainCalls.isValidBoard.loc[complainCalls['Community Board'] == bname] = np.nan

In [245]:
# print (len(complainCalls))
# Drop the marked invalid districts

# Drop the marked districts
complainCalls = complainCalls[~complainCalls['isValidBoard'].isnull()]

In [246]:
# Check the new number of complains (from valid districts only)
#print (len(complainCalls))

8110923

In [252]:
# Aggregate the data
complainCallsPerCommunityBoard = complainCalls[['Community Board','Agency']].groupby(["Community Board"], 
                                                                                     as_index=False).agg('count')

In [268]:
# Display the aggregated dataset by descending order of complains per community

complainCallsPerCommunityBoard.rename(columns={'Agency' : 'Complains'}, inplace=True)
complainCallsPerCommunityBoard = complainCallsPerCommunityBoard.sort('Complains', ascending=False)

print (complainCallsPerCommunityBoard)

               cd_id  Complains
49      12 MANHATTAN     268053
50         12 QUEENS     229383
11       03 BROOKLYN     197305
30         07 QUEENS     195961
57       17 BROOKLYN     191720
20       05 BROOKLYN     189765
53       14 BROOKLYN     187792
27          07 BRONX     185729
1        01 BROOKLYN     185057
4   01 STATEN ISLAND     182708
15          04 BRONX     181953
3          01 QUEENS     171484
22         05 QUEENS     168570
47          12 BRONX     168455
52         13 QUEENS     163851
19          05 BRONX     161078
58       18 BROOKLYN     156100
29      07 MANHATTAN     151419
38         09 QUEENS     151242
48       12 BROOKLYN     150320
12      03 MANHATTAN     150296
33      08 MANHATTAN     149076
35          09 BRONX     147457
55       15 BROOKLYN     146129
21      05 MANHATTAN     142028
32       08 BROOKLYN     141118
44       11 BROOKLYN     139890
16       04 BROOKLYN     139702
41      10 MANHATTAN     137344
14  03 STATEN ISLAND     136487
36       09 BROOKLYN     135830
7       02 MANHATTAN     133860
17      04 MANHATTAN     132659
42         10 QUEENS     128116
37      09 MANHATTAN     127564
34         08 QUEENS     123131
43          11 BRONX     122079
13         03 QUEENS     122009
9   02 STATEN ISLAND     121132
6        02 BROOKLYN     121021
8          02 QUEENS     114333
24       06 BROOKLYN     114029
40       10 BROOKLYN     111837
28       07 BROOKLYN     107031
25      06 MANHATTAN     104249
54         14 QUEENS     103396
46         11 QUEENS     101908
23          06 BRONX      99547
18         04 QUEENS      99316
39          10 BRONX      95496
45      11 MANHATTAN      95413
31          08 BRONX      92733
26         06 QUEENS      90938
56       16 BROOKLYN      85466
2       01 MANHATTAN      77974
10          03 BRONX      75134
0           01 BRONX      74631
51       13 BROOKLYN      72362
5           02 BRONX      60257

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:4: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

#### 4. Interpretation of the results
Explore in more detail the underlying dempgraphics/infrastructure of a Community District, as this data might influence 311 calls. 

We will merge the external data on the Community District level to your analysis data.

In [320]:
# Load the dataset with the Demographics info
# http://cosmo.nyu.edu/~fb55/PUI2016/data/
df_pop = pd.read_csv("http://cosmo.nyu.edu/~fb55/PUI2016/data/Final_Demographics.csv")

In [316]:
# Display the columns of the dataset
df_pop.columns

Index([u'FIPS', u'cd_id', u'Total Population',
       u'Population Density (per sq. mile)', u'% Total Population: Male',
       u'% Total Population: 18 to 24 Years',
       u'% Total Population: 25 to 34 Years',
       u'% Total Population: 35 to 44 Years',
       u'% Population 5 Years And Over: Speak Only English',
       u'% Population 5 Years And Over: Spanish or Spanish Creole',
       ...
       u'Employed Civilian Population 16 Years And Over: Production, transportation, and material moving  occupations: Production occupations',
       u'Employed Civilian Population 16 Years And Over: Production, transportation, and material moving  occupations: Transportation and material moving occupations',
       u'% Employed Civilian Population 16 Years And Over: Management, professional, and related occupations',
       u'% Employed Civilian Population 16 Years And Over: Service occupations',
       u'% Employed Civilian Population 16 Years And Over: Sales and office occupations',
       u'% Employed Civilian Population 16 Years And Over: Farming, fishing, and forestry occupations',
       u'% Employed Civilian Population 16 Years And Over: Construction, extraction, and maintenance  occupations',
       u'% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving  occupations',
       u'% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving  occupations: Production occupations',
       u'% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving  occupations: Transportation and material moving occupations'],
      dtype='object', length=158)

In [321]:
# Get familiar with the values and try to identity a matching column for the merge
df_pop
df_pop.cd_id.unique

<bound method Series.unique of 0        BX08
1        BX12
2        BX10
3        BX11
4        BX03
5        BX06
6        BX07
7        BX05
8        BX04
9        BX09
10       BX01
11       BX02
12       MN12
13       MN09
14       MN10
15    MN11111
16       MN08
17       MN07
18       MN05
19       MN04
20       MN06
21       MN03
22       MN01
23       MN02
24       SI03
25       SI02
26       SI01
27       BK01
28       BK04
29       BK03
30       BK02
31       BK06
32       BK08
33       BK16
34       BK05
35       BK18
36       BK17
37       BK09
38       BK07
39       BK10
40       BK12
41       BK14
42       BK15
43       BK11
44       BK13
45       QN01
46       QN03
47       QN07
48       QN11
49       QN13
50       QN08
51       QN04
52       QN06
53       QN02
54       QN05
55       QN09
56       QN12
57       QN10
58       QN14
Name: cd_id, dtype: object>

In [322]:
# cd_id looks like a good candidate, but needs to be reformated
# Parse the values, separate the two letter borrough code, convert into full bourough name and refer the code of the district
# So they match the complainCallsPerCommunityBoard dataset Community Board format

df_pop['cd_id'] = df_pop['cd_id'].map(lambda x: x.replace('QN', 'QUEENS '))
df_pop['cd_id'] = df_pop['cd_id'].map(lambda x: x.replace('BX', 'BRONX '))
df_pop['cd_id'] = df_pop['cd_id'].map(lambda x: x.replace('MN', 'MANHATTAN '))
df_pop['cd_id'] = df_pop['cd_id'].map(lambda x: x.replace('BK', 'BROOKLYN '))
df_pop['cd_id'] = df_pop['cd_id'].map(lambda x: x.replace('SI', 'STATEN ISLAND '))

In [323]:
df_pop['cd_id'].str.split(' ')[i][2] + ' ' + (df_pop['cd_id'].str.split(' '))[i][0] + ' ' + (df_pop['cd_id'].str.split(' '))[i][1]

IndexError: list index out of range

In [324]:

for i in range (0,len(df_pop)):
    if (df_pop['cd_id'][i][0] == 'S'):
        df_pop['cd_id'][i] = (df_pop['cd_id'].str.split(' '))[i][2] + ' ' + (df_pop['cd_id'].str.split(' '))[i][0] \
            + ' ' + (df_pop['cd_id'].str.split(' '))[i][1]
    else:
        df_pop['cd_id'][i] = (df_pop['cd_id'].str.split(' '))[i][1] + ' ' + (df_pop['cd_id'].str.split(' '))[i][0]

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [326]:
# print (df_pop)

In [327]:
# Renanme Columns for esier merge
complainCallsPerCommunityBoard.rename(columns={'Community Board' : 'cd_id'}, inplace=True)
complainCallsPerCommunityBoard['cd_id']

# Merge both datasets
merged_data = pd.merge(df_pop, complainCallsPerCommunityBoard, on='cd_id')

In [328]:
# Visualize
merged_data

,FIPS,cd_id,Total Population,Population Density (per sq. mile),% Total Population: Male,% Total Population: 18 to 24 Years,% Total Population: 25 to 34 Years,% Total Population: 35 to 44 Years,% Population 5 Years And Over: Speak Only English,% Population 5 Years And Over: Spanish or Spanish Creole,...,"Employed Civilian Population 16 Years And Over: Production, transportation, and material moving occupations: Transportation and material moving occupations","% Employed Civilian Population 16 Years And Over: Management, professional, and related occupations",% Employed Civilian Population 16 Years And Over: Service occupations,% Employed Civilian Population 16 Years And Over: Sales and office occupations,"% Employed Civilian Population 16 Years And Over: Farming, fishing, and forestry occupations","% Employed Civilian Population 16 Years And Over: Construction, extraction, and maintenance occupations","% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving occupations","% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving occupations: Production occupations","% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving occupations: Transportation and material moving occupations",Complains
0,3603701,08 BRONX,106737,31229.950060,46.65,10.73,15.04,11.32,46.80,39.24,...,1518,42.66,28.95,20.89,0.24,2.65,4.60,1.40,3.20,92733
1,3603702,12 BRONX,134644,19966.678390,46.35,11.35,14.29,12.57,73.09,18.19,...,4174,29.57,33.98,20.40,0.00,7.08,8.97,1.95,7.02,168455
2,3603703,10 BRONX,121209,12913.817030,45.20,8.62,13.74,12.78,61.79,26.43,...,3433,36.20,22.85,25.09,0.00,7.68,8.18,1.76,6.42,95496
3,3603704,11 BRONX,135839,35677.954530,50.09,8.10,17.43,14.09,43.22,36.45,...,5592,30.06,27.86,22.24,0.00,7.03,12.81,3.60,9.20,122079
4,3603705,03 BRONX,172247,39405.792220,44.72,14.24,14.89,12.38,36.82,54.24,...,5436,16.80,41.00,22.29,0.03,8.45,11.43,2.39,9.04,75134
5,3603705,06 BRONX,172247,39405.792220,44.72,14.24,14.89,12.38,28.21,59.53,...,5436,16.80,41.00,22.29,0.03,8.45,11.43,2.39,9.04,99547
6,3603706,07 BRONX,135893,86487.077920,48.48,10.58,14.97,15.32,29.10,62.49,...,4653,21.49,31.83,24.74,0.00,9.34,12.60,4.51,8.09,185729
7,3603707,05 BRONX,132850,87974.348600,45.75,13.10,16.34,11.96,29.84,59.43,...,5345,16.10,39.78,21.56,0.11,8.19,14.26,3.78,10.48,161078
8,3603708,04 BRONX,141467,71270.882190,45.64,12.28,12.41,13.10,42.97,47.55,...,6444,17.47,37.11,23.89,0.00,6.03,15.50,3.33,12.17,181953
9,3603709,09 BRONX,190126,42752.506900,47.59,11.15,15.22,12.54,33.62,61.02,...,7466,22.34,29.50,24.34,0.00,10.17,13.65,3.97,9.68,147457
10,3603710,01 BRONX,167147,34412.075240,49.63,12.76,18.26,12.04,27.49,66.53,...,5806,17.71,39.30,22.68,0.00,5.70,14.61,3.39,11.22,74631
11,3603710,02 BRONX,167147,34412.075240,49.63,12.76,18.26,12.04,49.63,36.01,...,5806,17.71,39.30,22.68,0.00,5.70,14.61,3.39,11.22,60257
12,3603801,12 MANHATTAN,224365,75217.432870,49.80,11.49,19.48,14.51,68.39,18.39,...,6077,32.55,32.34,18.99,0.00,6.70,9.42,3.68,5.74,268053
13,3603802,09 MANHATTAN,130739,77402.950100,48.06,19.14,19.88,12.03,47.08,40.57,...,2361,46.06,23.09,22.66,0.00,2.60,5.58,1.63,3.95,127564
14,3603803,10 MANHATTAN,132027,91244.889890,43.68,8.89,20.81,14.77,74.19,6.94,...,2661,44.46,22.40,23.82,0.00,3.34,5.98,1.55,4.43,137344
15,3603805,08 MANHATTAN,221898,109960.139600,42.11,4.03,24.19,15.73,67.27,11.53,...,765,70.55,4.79,22.18,0.00,1.77,0.71,0.13,0.58,149076
16,3603806,07 MANHATTAN,192374,65024.961090,46.37,5.38,17.74,14.88,73.38,6.42,...,1302,72.22,8.10,14.91,0.00,2.40,2.37,1.19,1.18,151419
17,3603807,05 MANHATTAN,149447,48626.990950,51.44,8.82,29.41,17.81,45.29,20.63,...,667,68.37,8.35,20.44,0.07,1.14,1.64,0.97,0.66,142028
18,3603807,04 MANHATTAN,149447,48626.990950,51.44,8.82,29.41,17.81,73.93,5.37,...,667,68.37,8.35,20.44,0.07,1.14,1.64,0.97,0.66,132659
19,3603808,06 MANHATTAN,143349,87333.791040,45.70,10.88,28.09,11.00,78.30,4.53,...,1140,72.16,5.75,18.85,0.00,1.32,1.92,0.70,1.22,104249
20,3603809,03 MANHATTAN,152453,87256.670150,50.34,10.72,21.18,13.66,63.29,6.74,...,1762,52.84,21.01,20.02,0.08,2.78,3.27,0.99,2.29,150296
21,3603810,01 MANHATTAN,159903,53928.053600,49.00,8.55,28.38,18.14,65.31,19.32,...,1404,73.33,4.22,19.67,0.00,0.75,2.04,0.65,1.39,77974
22,3603810,02 MANHATTAN,159903,53928.053600,49.00,8.55,28.38,18.14,44.94,22.34,...,1404,73.33,4.22,19.67,0.00,0.75,2.04,0.65,1.39,133860
23,3603901,03 STATEN ISLAND,170741,6968.306388,48.87,8.46,11.03,13.69,36.45,57.06,...,4524,45.70,15.12,23.52,0.00,7.75,7.91,1.98,5.93,136487
24,3603902,02 STATEN ISLAND,126200,6371.997113,46.29,7.82,12.51,12.48,68.91,16.56,...,2615,37.76,18.64,24.65,0.00,11.48,7.46,2.88,4.58,121132
25,3603903,01 STATEN ISLAND,176338,12537.604960,49.29,10.93,15.08,12.94,71.43,13.59,...,4911,35.67,26.10,21.81,0.08,7.50,8.83,2.32,6.51,182708
26,3604001,01 BROOKLYN,154713,37671.510580,49.93,8.52,29.88,13.70,72.48,15.53,...,2894,52.80,15.35,22.83,0.00,3.47,5.55,2.14,3.40,185057
27,3604002,04 BROOKLYN,137368,54279.761230,48.98,14.57,24.00,13.76,78.17,9.87,...,4236,32.48,26.22,20.84,0.78,9.73,9.94,3.69,6.25,139702
28,3604003,03 BROOKLYN,133235,58004.868160,47.55,12.75,19.43,11.55,77.10,17.30,...,3220,38.00,25.77,23.45,0.34,4.57,7.87,2.39,5.48,197305
29,3604004,02 BROOKLYN,139070,44719.888150,45.99,9.57,22.68,17.05,57.49,32.56,...,1830,61.18,12.70,19.14,0.25,2.56,4.18,1.65,2.53,121021
30,3604005,06 BROOKLYN,125062,31218.503280,48.71,4.79,22.77,21.13,69.33,6.48,...,1121,72.16,6.67,16.34,0.00,2.30,2.53,0.94,1.59,114029
31,3604006,08 BROOKLYN,126747,57010.543560,46.57,10.12,19.57,16.61,80.23,5.63,...,3774,39.90,26.36,21.15,0.00,4.91,7.68,1.53,6.15,141118
32,3604007,16 BROOKLYN,123772,47796.011830,43.49,9.36,15.89,12.49,71.10,7.96,...,2507,20.53,39.80,23.63,0.00,7.19,8.85,2.95,5.90,85466
33,3604008,05 BROOKLYN,155863,26394.764690,45.49,11.18,15.29,12.60,25.03,37.69,...,4407,22.95,31.85,26.95,0.00,6.98,11.27,4.11,7.16,189765
34,3604009,18 BROOKLYN,210957,15374.526180,46.98,9.99,13.65,13.47,44.62,9.48,...,7813,35.45,25.48,22.08,0.11,6.91,9.98,2.21,7.77,156100
35,3604010,17 BROOKLYN,137526,44659.444610,42.60,9.34,14.79,13.25,31.11,10.81,...,4202,29.73,32.56,22.41,0.00,7.91,7.39,0.79,6.60,191720
36,3604011,09 BROOKLYN,109337,64006.179970,45.55,11.44,20.14,12.49,50.85,13.08,...,2414,41.95,24.92,20.82,0.00,5.68,6.63,1.86,4.76,135830
37,3604012,07 BROOKLYN,152685,36736.915040,49.70,9.38,19.44,16.10,43.33,5.24,...,3886,28.47,33.45,19.57,0.05,7.42,11.04,5.77,5.27,107031
38,3604013,10 BROOKLYN,128545,33069.986680,48.47,7.29,17.02,14.02,27.63,10.75,...,3837,41.93,20.93,23.51,0.00,4.20,9.44,3.10,6.34,111837
39,3604014,12 BROOKLYN,170011,54054.487510,50.97,8.66,14.25,12.58,31.65,10.94,...,3622,35.73,20.84,27.19,0.47,7.77,8.00,2.30,5.70,150320
40,3604015,14 BROOKLYN,180723,62164.359800,46.21,9.68,16.91,12.37,41.83,24.16,...,6774,38.94,25.20,18.74,0.00,6.28,10.85,2.42,8.42,187792
41,3604016,15 BROOKLYN,137815,31829.054410,47.84,7.06,14.92,11.11,16.12,62.45,...,3571,39.86,20.21,25.24,0.00,5.73,8.96,3.21,5.75,146129
42,3604017,11 BROOKLYN,187637,50644.631520,49.73,7.63,15.81,14.55,27.57,14.80,...,5977,30.95,24.92,23.02,0.17,8.98,11.97,4.95,7.02,139890
43,3604018,13 BROOKLYN,110727,32537.409220,45.85,8.33,10.34,11.27,40.57,9.00,...,3720,32.61,24.37,21.09,0.23,8.34,13.36,4.42,8.94,72362
44,3604101,01 QUEENS,182860,35800.759600,49.32,9.26,27.12,15.74,66.19,9.25,...,6218,41.74,21.52,21.93,0.03,6.26,8.51,2.48,6.03,171484
45,3604102,03 QUEENS,182354,44839.980490,50.10,8.48,18.96,16.20,40.08,15.70,...,8804,21.71,32.46,19.76,0.06,11.04,14.96,5.15,9.81,122009
46,3604103,07 QUEENS,256742,21836.668490,47.61,8.43,14.06,13.96,15.29,48.07,...,6750,31.41,28.34,23.03,0.18,7.83,9.22,3.56,5.66,195961
47,3604104,11 QUEENS,120996,12991.169540,49.38,6.24,13.72,13.04,36.98,12.56,...,1693,47.08,14.87,26.07,0.00,7.13,4.85,1.97,2.88,101908
48,3604105,13 QUEENS,193102,9812.563966,46.91,9.45,12.90,13.14,27.17,30.49,...,9082,32.21,23.15,26.46,0.00,6.16,12.01,2.35,9.66,163851
49,3604106,08 QUEENS,159330,21412.216470,46.58,9.96,15.41,13.35,47.31,25.29,...,4542,39.59,19.14,28.03,0.00,4.53,8.70,2.62,6.09,123131
50,3604107,04 QUEENS,154740,42497.737460,52.21,10.22,18.95,13.72,40.05,34.50,...,6448,22.15,37.36,17.17,0.00,10.34,12.98,4.13,8.85,99316
51,3604108,06 QUEENS,107893,38598.784620,45.82,5.21,13.35,15.97,71.64,14.65,...,1744,53.76,14.01,22.96,0.00,2.90,6.37,3.19,3.18,90938
52,3604109,02 QUEENS,150100,25142.587280,52.05,7.88,21.98,17.65,65.22,19.14,...,9840,32.24,24.29,19.25,0.00,6.48,17.74,5.74,12.00,114333
53,3604110,05 QUEENS,168488,23005.322980,48.94,9.48,14.84,15.10,68.93,18.09,...,5899,30.56,22.93,23.80,0.00,11.75,10.96,3.80,7.15,168570
54,3604111,09 QUEENS,151202,31804.100680,48.58,10.89,16.24,14.68,NaN,NaN,...,8173,26.76,24.70,23.37,0.17,10.00,15.00,3.48,11.52,151242
55,3604112,12 QUEENS,251002,27089.677200,46.33,10.22,14.74,12.73,NaN,NaN,...,10217,27.46,30.09,24.48,0.00,6.36,11.60,2.58,9.02,229383
56,3604113,10 QUEENS,134827,21979.770830,48.24,9.37,12.33,14.90,NaN,NaN,...,5224,24.79,23.40,28.96,0.00,11.19,11.66,3.30,8.35,128116
57,3604114,14 QUEENS,107944,9541.923526,48.36,7.78,11.68,10.32,NaN,NaN,...,2506,35.75,25.83,22.06,0.00,6.80,9.56,3.49,6.07,103396